from . import ojt_batch
from . import ojt_event_link
from . import ojt_assignment
from . import ojt_assignment_submit
from . import ojt_participant
from . import ojt_attendance
from . import ojt_progress
from . import ojt_certificate
from . import ojt_meeting_attendance
from . import ojt_gamification
from . import ojt_proctoring
